config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root to: "pages#bienvenue"

  get "/accueil", to: "pages#accueil"

  resources :clubs, only: %i[index show]

  resources :players, only: %i[index show edit update] do
    collection do
      get "filter_by_position"
    end
    resources :bookings, only: %i[show new create]
  end

  resource :dashboard, only: %i[show]

  namespace :dashboard do
    resources :players, only: %i[index] do
      collection do
        get :loaned_out
        get :loaned_in
      end
    end
    resources :bookings, only: %i[index show] do
      member do
        patch :accept
        patch :refuse
      end
    end
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :club
  has_many :bookings

  enum :position, { gardien: 0, defenseur: 1, milieu: 2, attaquant: 3, polyvalent: 4 }, default: :polyvalent
  enum :status, { unavailable: 0, rented: 1, available: 2 }, default: :available

  def self.by_position(requested_position)
    if requested_position == "all"
      all
    elsif positions.key?(requested_position)
      where(position: requested_position)
    else
      none
    end
  end

  def update_availability_status!
    today = Date.current

    is_player_on_loan = Booking.where(player_id: self.id, status: :accepted)
                                .where(start_date: ..today)
                                .where(end_date: today..)
                                .exists?

    if is_player_on_loan
      unless self.rented?
        self.rented!
      end
    else
      unless self.available?
        self.available!
      end
    end
  end
end

app/controllers/dashboard/players_controller.rb
class Dashboard::PlayersController < Dashboard::BaseController
  before_action :set_club
  def index
    @players = @club.players
  end

  def loaned_out
    @loaned_out_players = @club.loaned_out_players.includes(:bookings)
  end

  def loaned_in
    @loaned_in_players = @club.loaned_in_players.includes(:bookings)
  end

  private

  def set_club
    @club = current_user.club
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [ :show, :edit, :update ]
  before_action :authenticate_user!, only: [ :edit, :update ]

  def index
    @positions = Player.positions.keys
    @players = policy_scope(Player)
  end

  def filter_by_position
    base_scope = policy_scope(Player)
    if params[:position].present?
      @players = base_scope.by_position(params[:position])
    else
      @players = base_scope.all
    end
    render partial: "player_card", collection: @players, as: :player
  end

  def show
    authorize @player
    if user_signed_in?
      authorize Booking, :new?
      @booking = Booking.new
    end
  end

  def edit
    authorize @player
  end

  def update
    authorize @player
  end

  private

  def set_player
    @player = Player.find(params[:id])
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_player_card.html.erb
<%= link_to player_path(player) do %>
  <div class="player-card w-64 xl:w-72 h-96 bg-black rounded-xl shadow-green shadow-lg overflow-hidden p-4 flex flex-col justify-between items-center">
    <div class="w-full flex justify-center items-center mb-2">
      <h4 class="text-center"><%= player.name %></h4>
    </div>
    <div class="w-full flex-grow flex items-center justify-center">
      <%= image_tag player.photo, class: "h-full object-contain drop-shadow-md rounded-xl" %>
    </div>
    <div class="w-full flex justify-between items-center mt-4">
      <div class="price-card flex items-center rounded-lg p-2 pr-3">
        <span class="text-3xl font-extrabold"><%= player.price_per_day %>€</span></div>
      <div class="w-10 h-10 flex items-center justify-center">
        <%= image_tag player.club.logo %>
      </div>
    </div>
  </div>
<% end %>

app/views/players/edit.html.erb
<div>
  <h1 class="font-bold text-4xl">Players#edit</h1>
  <p>Find me in app/views/players/edit.html.erb</p>
</div>

app/views/players/index.html.erb
<div class="container" data-controller="players-filter">
  <button class="btn-green fixed bottom-7 right-7 z-20 p-6 rounded-full" type="button" data-action="players-filter#toggleSideBar"></button>
  <div data-players-filter-target="menu" class="hidden sidebar fixed inset-y-0 left-0 p-6 z-40 w-3/4 max-w-xs green-bg shadow-green shadow-xl duration-300 ease-out">
    <button type="button"
        class="absolute top-6 right-6 p-1 text-green-100 hover:text-white"
        data-action="players-filter#toggleSideBar">
      <span class="text-2xl leading-none">&times;</span>
    </button>
    <h3>Filtres</h3>
    <ul class="list-none flex flex-col gap-y-1">
      <li>
        <%= link_to "Tous les joueurs", players_path, id: 'all-players-link',
      data: {
        action: "players-filter#filter players-filter#toggleSideBar",
        filter_position: 'all'} %>
      </li>
      <% @positions.each do |position| %>
        <li>
          <%= link_to position.capitalize, players_path(position: position),
          data: {
            action: "players-filter#filter players-filter#toggleSideBar",
            filter_position: position } %>
        </li>
      <% end %>
    </ul>
  </div>
  <div data-players-filter-target="overlay" class="hidden md:hidden fixed inset-0 bg-black/50 z-30 transition-opacity duration-300 ease-in-out"></div>
  <div data-players-filter-target="list" class="flex flex-col items-center my-10 gap-12 md:grid md:grid-cols-2 md:gap-20 md:justify-self-center lg:grid-cols-3 2xl:grid-cols-4">
    <%= render partial: 'player_card', collection: @players, as: :player %>
  </div>
</div>

app/views/players/show.html.erb
<div class="mt-4 gradient"></div>
<%= image_tag (@player.photo), class:"w-48 h-auto object-cover mx-auto my-4 rounded-2xl" %>
<h1 class="text-center pb-4"><%= @player.name.upcase %></h1>
<div class="green-bg w-full rounded-t-2xl rounded-b-2xl py-4 shadow-green my-4 mx-auto grid grid-cols-1 md:w-[95%] lg:grid-cols-4 lg:w-[80%]">
  <div class="lg:grid lg:col-span-2 lg:col-start-1 w-[95%] mx-auto">
    <div class="flex flex-col gap-2 justify-center items-center w-[90%] border-b-1 mx-auto border-b-neutral-400 py-4">
      <h2 id="position"><%= t("activerecord.enums.player.position.#{@player.position}") %></h2>
      <h5><%= @player.club.name %></h5>
      <%= image_tag (@player.club.logo), class:"w-14 h-14" %>
    </div>
    <div class="flex flex-col gap-4 justify-start align-center w-[95%] mx-auto py-8 px-4 border-b-1 border-b-neutral-400">
      <div class="infos-player">
        <h5>Pied</h5>
        <i class="fa-solid fa-shoe-prints"></i>
        <p>Pied <%= @player.foot %></p>
      </div>
      <div class="infos-player">
        <h5>Age</h5>
        <i class="fa-solid fa-cake-candles"></i>
        <p><%= @player.age %> ans</p>
      </div>
      <div class="infos-player">
        <h5>Taille</h5>
        <i class="fa-solid fa-ruler"></i>
        <p><%= @player.height %> cm</p>
      </div>
      <div class="infos-player">
        <h5>Valeur sur le marché</h5>
        <i class="fa-solid fa-money-check-dollar"></i>
        <p><%= @player.market_value %> €</p>
      </div>
    </div>
  </div>
  <div class="m-4 lg:col-span-2 lg:col-start-3 w-[90%] md:w-[80%] lg:w-[70%] mx-auto">
    <%= render "bookings/form", booking: @booking %>
  </div>
</div>

app/views/players/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Players#update</h1>
  <p>Find me in app/views/players/update.html.erb</p>
</div>