config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root to: "pages#bienvenue"

  get "/accueil", to: "pages#accueil"

  resources :clubs, only: %i[index show]

  resources :players, only: %i[index show edit update] do
    collection do
      get "filter_by_position"
    end
    resources :bookings, only: %i[show new create]
  end

  resource :dashboard, only: %i[show]

  namespace :dashboard do
    resources :players, only: %i[index] do
      collection do
        get :loaned_out
        get :loaned_in
      end
    end
    resources :bookings, only: %i[index show] do
      member do
        patch :accept
        patch :refuse
      end
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="w-full p-4">
  <div class="footer-container max-w-[1400px] mx-auto flex flex-col gap-6 md:flex-row md:p-6 md:justify-between">
    <div class="text-footer black-bg">
      <h3>New Mercato</h3>
      <span><%= link_to 'Joueurs', players_path %></span>
      <span><%= link_to 'Clubs', root_path %></span>
      <span><%= link_to 'Statistiques', root_path %></span>
    </div>
    <div class="text-footer black-bg">
      <h3>Rejoignez-nous</h3>
      <span><%= link_to 'Contactez-nous', root_path %></span>
      <span><%= link_to 'Qui sommes-nous ?', root_path %></span>
      <span><%= link_to 'Et après ?', root_path %></span>
    </div>
    <div class="text-footer black-bg">
      <h3>Mentions légales</h3>
      <span><%= link_to 'Mentions légales du site', root_path %></span>
      <span><%= link_to 'Conditions générales', root_path %></span>
    </div>
  </div>
</footer>
<div class="footer-banner flex justify-center green-bg w-full">
  <p class="scale-80">Copyright. Tous droits réservés.</p>
</div>

app/views/layouts/_navbar.html.erb
<header class="w-full black-bg">
  <nav class="w-full relative" data-controller="mobile-menu">
    <div class="w-[95%] mx-auto  flex justify-between items-center h-[7vh] md:h-[9vh]">
      <%= image_tag 'NewMercato.PNG', id:"logo-img" %>
      <div class="hidden md:flex flex-row items-center space-x-10">
        <%= link_to players_path do %>
          <h5>Joueurs</h5>
        <% end %>
        <%= link_to root_path do %>
          <h5>Statistiques</h5>
        <% end %>
        <%= link_to clubs_path do %>
          <h5>Clubs</h5>
        <% end %>
        <% if user_signed_in? %>
          <%= link_to dashboard_path do %>
            <p>Tableau de bord</p>
          <% end %>
          <%= link_to destroy_user_session_path, data: { turbo_method: :delete } do %>
            <p>Déconnexion</p>
          <% end %>
        <% else %>
          <%= link_to new_user_session_path do %>
            <p>Connexion</p>
          <% end %>
        <% end %>
      </div>
      <div class="md:hidden flex items-center"  >
        <button class="menu-button" data-mobile-menu-target="button" data-action="click->mobile-menu#toggle">
          <span></span>
          <span></span>
          <span></span>
        </button>
        <div class="mobile-menu" data-mobile-menu-target="tabs">
          <%= link_to players_path do %>
            <h5>Joueurs</h5>
          <% end %>
          <%= link_to root_path do %>
            <h5>Statistiques</h5>
          <% end %>
          <%= link_to clubs_path do %>
            <h5>Clubs</h5>
          <% end %>
          <% if user_signed_in? %>
            <%= link_to dashboard_path do %>
              <p>Tableau de bord</p>
            <% end %>
            <%= link_to destroy_user_session_path, data: { turbo_method: :delete } do %>
              <p>Déconnexion</p>
            <% end %>
          <% else %>
            <%= link_to new_user_session_path do %>
              <p>Connexion</p>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <title><%= content_for(:title) || "New Mercato" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <link href="https://cdn.jsdelivr.net/npm/vanilla-calendar-pro/styles/index.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/5ae925a9ee.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="w-full min-h-screen flex flex-col overflow-auto m-0 p-0">
    <% unless current_page?(root_path) %>
      <%= render "layouts/navbar" %>
    <% end %>
    <main class="flex-1">
      <%= render "shared/flash_messages" %>
      <%= yield %>
    </main>
    <% unless current_page?(root_path) %>
      <%= render "layouts/footer" %>
    <% end %>
  </body>
</html>